### ISSUE TITLE
ebooks archive returns 401Unautorized

### ISSUE THREAD

**Issue by Altazon97** [mispy/ebooks_example#12]
My bot was working properly, but just a few hours ago had I received a 401 error.  Unable to find the problem, I ran:

rvm implode
gem uninstall rvm

and reinstalled my whole Ruby system so it's brand new.  Now, whenever I try to get an archive of a user's tweets, it still returns the same error, which is below:

Erics-MacBook-Pro:ebooks_example eric$ ebooks archive epsund corpus/epsund.json
New archive for @epsund at corpus/epsund.json
/Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete': Could not authenticate you. (Twitter::Error::Unauthorized)
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/request/multipart.rb:14:in `call'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/request.rb:33:in `perform'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:51:in `perform_request'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/utils.rb:140:in `objects_from_response_with_user'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter-5.13.0/lib/twitter/rest/timelines.rb:49:in `user_timeline'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/lib/twitter_ebooks/archive.rb:76:in `block in sync'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/lib/twitter_ebooks/archive.rb:74:in `loop'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/lib/twitter_ebooks/archive.rb:74:in `sync'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/bin/ebooks:150:in `archive'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/bin/ebooks:322:in `command'
	from /Users/eric/.rvm/gems/ruby-2.1.3/gems/twitter_ebooks-3.0.0/bin/ebooks:339:in `<top (required)>'
	from /Users/eric/.rvm/gems/ruby-2.1.3/bin/ebooks:23:in `load'
	from /Users/eric/.rvm/gems/ruby-2.1.3/bin/ebooks:23:in `<main>'
	from /Users/eric/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/eric/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'

I've attempted redoing this process with rvm 1.9.3, 2.0.0, and 2.1.3, but no luck.  It keeps giving this error.  These are all the commands I've ran to this point:

git clone https://github.com/mispy/ebooks_example.git
bundle install
gem install twitter_ebooks
rvm use 2.1.3
//then, populated bots.rb with correct access key/tokens and consumer key/secrets for the BOT'S ACCOUNT.
ebooks archive epsund corpus/epsund.json

Is there something I'm missing?

Thanks.

**Comment by BooDoo** [comment]
Hi, and sorry for the delay. 

Using the library as hosted in this repo, you do **not** put your keys/secrets into bots.rb. They should be set as environment variables instead. (see `app.json` for the names of the variables)

**Comment by ghost** [comment]
`ebooks auth`
It worked for me.
